# Basic Elasticsearch settings
cluster.name: "reddit-worldnews-cluster"
node.name: "reddit-worldnews-node"
network.host: 0.0.0.0
discovery.type: single-node

# Security settings for anonymous access
xpack.security.enabled: true
xpack.security.http.ssl.enabled: false
xpack.security.authc.anonymous:
  username: "kibana_dashboard_user"
  roles: ["kibana_dashboard_only"]
  authz_exception: false

# Performance settings
bootstrap.memory_lock: false
